server:
  port: 8083


#  dataSource
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/rebirth?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

# jsp 映射
    mvc:
        view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp

# redis
    redis:
          host: 127.0.0.1
          port: 6379
          database: 0
          password:
          pool:
              max-active: 8
              max-wait: 1
              min-idle: 0
          timeout: 0


#  mybatis 映射
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hk.rebirth.pojo

#  # redis
#  # Redis数据库索引（默认为0）
#  spring.redis.database=0
#  # Redis服务器地址
#  spring.redis.host=47.100.54.6
#  # Redis服务器连接端口
#  spring.redis.port=6379
#  # Redis服务器连接密码（默认为空）
#  spring.redis.password=
#  # 连接池最大连接数（使用负值表示没有限制）
#  spring.redis.pool.max-active=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.pool.max-wait=-1
#  # 连接池中的最大空闲连接
#  spring.redis.pool.max-idle=8
#  # 连接池中的最小空闲连接
#  spring.redis.pool.min-idle=0
#  # 连接超时时间（毫秒）
#  spring.redis.timeout=0
